name: Krzysztof Stańkowski
description: >
    Specjalistyczna Praktyka Psychiatryczna
about: >
    

master_repo: false
url: "https://ztankoz.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           ztankoz
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "praktyka@gabinetpsychiatra.pl"
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/ztankoz
  
# Analytics and webmaster tools stuff goes here