name: Krzysztof Stańkowski
description: Specjalistyczna Praktyka Psychiatryczna
about: Gabinet lekarski
    

master_repo: false
url: "https://ztankoz.github.io/praktyka"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           ztankoz
  email:          "praktyka@gabinetpsychiatra.pl"
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/ztankoz
  
# Analytics and webmaster tools stuff goes here
include: [".well-known"]